/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mars-156a95dfec244e07a3ae423f579ffb05
title: Mars
*/

import React, { useRef, Suspense, useState } from "react";
import {
  CameraControls,
  Center,
  Stars,
  useProgress,
  Html,
} from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { Button } from "@/app/components/Button";


function Loader() {
  const { progress } = useProgress();
  return <Html center>{progress.toFixed(2)} % loaded</Html>;
}

const MarteModel = (props) => {
  const { nodes, materials } = useGLTF("/marte.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, -2.5, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mars_LOD0_MarsLOD1_0.geometry}
                material={materials.MarsLOD1}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export const Marte = () => {

  const [isfull, setFull] = useState(false);
  const container = useRef();

  const cameraControlsRef = useRef();

  const handleRecentralize = () => {
    cameraControlsRef.current?.reset(true);
  };

  const handleFullScreen = () => {
    if (!isfull) {
      container.current.requestFullscreen();
      container.current.requestPointerLock();
      setFull(true);
    } else {
      document.exitFullscreen();
      setFull(false);
    }
  }

  function RotatingObject() {
    const meshRef = useRef();
    const [rotation, setRotation] = useState(0);

    useFrame(() => {
      setRotation((prevRotation) => prevRotation + 0.0005);
      meshRef.current.rotation.y = rotation;
    });

    return (
      <mesh ref={meshRef}>
        <Stars
          radius={100}
          depth={50}
          count={5000}
          factor={4}
          saturation={0}
          fade={true}
        />
        <Html>
          <Button onClick={handleRecentralize}>
            <span>Recentralizar</span>
          </Button>
          <Button onClick={handleFullScreen}>
            <span>Tela inteira</span>
          </Button>
        </Html>
        <Center>
          <MarteModel />
        </Center>
      </mesh>
    );
  }

  return (
    <div className="container">
    <Canvas ref={container} camera={{ position: [5, 2, 5], fov: 60 }} >
    <Suspense fallback={<Loader />}>
      <RotatingObject />
      <ambientLight intensity={0.5} />
      <CameraControls truck={false} minDistance={4} maxDistance={30} ref={cameraControlsRef} />
    </Suspense>
  </Canvas>
  </div>
  )
}

useGLTF.preload("/marte.glb");
