/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mars-156a95dfec244e07a3ae423f579ffb05
title: Mars
*/

import React, { useRef, Suspense } from "react";
import {
  OrbitControls,
  Center,
  Sparkles,
  useProgress,
  Html,
} from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

function Loader() {
  const { progress } = useProgress();
  return <Html center>{progress.toFixed(2)} % loaded</Html>;
}

const MarteModel = (props) => {
  const { nodes, materials } = useGLTF("/marte.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, -2.5, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mars_LOD0_MarsLOD1_0.geometry}
                material={materials.MarsLOD1}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

export const Marte = () => {
  return (
    <Canvas camera={{ position: [2, 2, 2], fov: 60 }} className={"canvas"}>
    <Suspense fallback={<Loader />}>
      <OrbitControls
        enableRotate={false}
        enablePan={false}
        enableZoom={false}
        autoRotate
        autoRotateSpeed={0.3}
      />
      <ambientLight intensity={0.2} />
      <Sparkles count={1000} scale={1111 * 2} size={1} speed={0.4}>
          <MarteModel />
      </Sparkles>
    </Suspense>
  </Canvas>
  )
}

useGLTF.preload("/marte.glb");
