/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NestaEric (https://sketchfab.com/Nestaeric)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/saturn-c09a1970148c43ad99db134a9d6d00b5
title: Saturn
*/
import React, { useRef, Suspense, useState } from "react";
import {
  CameraControls,
  Center,
  Stars,
  useProgress,
  Html,
} from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { Button } from "@/app/components/Button";


function Loader() {
  const { progress } = useProgress();
  return <Html center>{progress.toFixed(2)} % loaded</Html>;
}

const SaturnoModel = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/saturn.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.76}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-0.42, Math.PI / 2, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.Saturn}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials.rings}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

export const Saturno = () => {

  const [isfull, setFull] = useState(false);
  const container = useRef();

  const cameraControlsRef = useRef();

  const handleRecentralize = () => {
    cameraControlsRef.current?.reset(true);
  };

  const handleFullScreen = () => {
    if (!isfull) {
      container.current.requestFullscreen();
      container.current.requestPointerLock();
      setFull(true);
    } else {
      document.exitFullscreen();
      setFull(false);
    }
  }

  function RotatingObject() {
    const meshRef = useRef();
    const [rotation, setRotation] = useState(0);

    useFrame(() => {
      setRotation((prevRotation) => prevRotation + 0.0005);
      meshRef.current.rotation.y = rotation;
    });

    return (
      <mesh ref={meshRef}>
        <Stars
          radius={100}
          depth={50}
          count={5000}
          factor={4}
          saturation={0}
          fade={true}
        />
        <Html>
          <Button onClick={handleRecentralize}>
            <span>Recentralizar</span>
          </Button>
          <Button onClick={handleFullScreen}>
            <span>Tela inteira</span>
          </Button>
        </Html>
        <Center>
          <SaturnoModel />
        </Center>
      </mesh>
    );
  }

  return (
    <div className="container">
    <Canvas ref={container} camera={{ position: [1.4, 1, 1.4], fov: 60 }} >
      <Suspense fallback={<Loader />}>
        <RotatingObject />
        <ambientLight intensity={0.15} />
        <CameraControls truck={false} minDistance={1} maxDistance={10} ref={cameraControlsRef} />
      </Suspense>
    </Canvas>
    </div>
  );
};

useGLTF.preload("/saturn.glb");
